#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/e5aa55e8-b2a0-42ed-84cc-131f6f660fb5/ # 
version: v1
title: CapstonProject

types: 
  userwithID: !include DataType/userwithID.raml
  userNoID: !include DataType/userNoID.raml
/users:
  description: This will get all users information!
  get:
   responses:
     200:
       description: 
       body:
         application/json:
           type: userwithID []
           example: !include Example/GetAllUsers.raml

  /{id}:
    description: This get method gets users by id
    get:
      responses:
        200:
          body:
            application/json:
              example: !include Example/getByID.raml
            
  post:
    description: This post method creates a new user!
    body:
      application/json:
        type: userNoID []
        example: !include Example/Post.raml
    
    responses: 
      201:
        body:
          application/json:
            example: 
              {"msg": "users information has created"}
            

  put:
    description: This method updates user!
    body:
      application/json:
        type: userwithID []
        example: !include Example/Put.raml
          
    responses:
      200:
        body:
          application/json:
            example:  
              {"msg": "users information updated"}

  delete:
    description: This method delets user by id!
    queryParameters:
      id:
        required: true
        type: integer       
    responses:
      200:
        body:
          application/json:
            example:
              {"msg": "User Information Deleted"}